In [1]:
import numpy.polynomial.polynomial as p
import scipy.linalg as la
import numpy as np


In [69]:
g =[0.25,0.75,1]
pg = [1,0.75,0.25,-1]

In [71]:
characteristic = p.Polynomial(pg)

In [72]:
croots=characteristic.roots()

In [73]:
characteristic

Polynomial([ 1.  ,  0.75,  0.25, -1.  ], domain=[-1,  1], window=[-1,  1])

In [74]:
p.polyvander(1/croots,3)**-1

array([[ 1.        -0.j        , -0.55095684-0.66040802j,
        -0.13258531+0.72771263j,  0.55363604-0.31337786j],
       [ 1.        -0.j        , -0.55095684+0.66040802j,
        -0.13258531-0.72771263j,  0.55363604+0.31337786j],
       [ 1.        -0.j        ,  1.35191369-0.j        ,
         1.82767062-0.j        ,  2.47085292-0.j        ]])

In [75]:
np.vander(croots,50).T

array([[-2.90453780e-04+5.46720209e-04j, -2.90453780e-04-5.46720209e-04j,
         2.60915134e+06+0.00000000e+00j],
       [-2.71776441e-04-6.66543800e-04j, -2.71776441e-04+6.66543800e-04j,
         1.92996888e+06+0.00000000e+00j],
       [ 7.97531683e-04+2.53826562e-04j,  7.97531683e-04-2.53826562e-04j,
         1.42758291e+06+0.00000000e+00j],
       [-8.20658431e-04+5.22986237e-04j, -8.20658431e-04-5.22986237e-04j,
         1.05597194e+06+0.00000000e+00j],
       [ 1.44334461e-04-1.12224012e-03j,  1.44334461e-04+1.12224012e-03j,
         7.81094197e+05+0.00000000e+00j],
       [ 8.94445445e-04+9.64760091e-04j,  8.94445445e-04-9.64760091e-04j,
         5.77769280e+05+0.00000000e+00j],
       [-1.52757613e-03+7.99761979e-05j, -1.52757613e-03-7.99761979e-05j,
         4.27371426e+05+0.00000000e+00j],
       [ 1.06640520e-03-1.42341229e-03j,  1.06640520e-03+1.42341229e-03j,
         3.16123307e+05+0.00000000e+00j],
       [ 4.76535579e-04+2.01232526e-03j,  4.76535579e-04-2.01232526e-03j

In [76]:
croots

array([-0.55095684-0.66040802j, -0.55095684+0.66040802j,
        1.35191369+0.j        ])

In [77]:
1/croots

array([-0.7448461 +0.89281464j, -0.7448461 -0.89281464j,
        0.73969219+0.j        ])

In [78]:
I = [1] # begin creation of infection list - 1 on day 0

forwardlist = [[1]*len(croots)] # list of zero powers of characteristic roots (i.e. 1)
backlist = forwardlist.copy()

for n in range(1,50):
    I = I + [0] # new entry
    for m in range(0,len(g)):
        if (n-m-1 >= 0): I[n] = I[n] + g[m]*I[n-m-1] # ensure that list indices remain non-negative
    forwardlist = forwardlist + [[forwardlist[n-1][m]*croots[m] for m in range(0,len(croots))]]
    backlist = backlist + [[backlist[n-1][m]/croots[m] for m in range(0,len(croots))]]


In [79]:
forwardlist

[[1, 1, 1],
 [(-0.5509568431231313-0.6604080182085825j),
  (-0.5509568431231313+0.6604080182085825j),
  (1.3519136862462644+0j)],
 [(-0.13258530752998077+0.7277126337708081j),
  (-0.13258530752998077-0.7277126337708081j),
  (1.827670615059963+0j)],
 [(0.553636040775155-0.3133778552137338j),
  (0.553636040775155+0.3133778552137338j),
  (2.470852918449692+0j)],
 [(-0.5119868135768266-0.19296800668390968j),
  (-0.5119868135768266+0.19296800668390968j),
  (3.340379877153664+0j)],
 [(0.15464501965717825+0.4444372406895292j),
  (0.15464501965717825-0.4444372406895292j),
  (4.515905273185654+0j)],
 [(0.20830718550682925-0.3469945500542827j),
  (0.20830718550682925+0.3469945500542827j),
  (6.105114144611361+0j)],
 [(-0.34392625245723474+0.0536112863196663j),
  (-0.34392625245723474-0.0536112863196663j),
  (8.253587368195754+0j)],
 [(0.22489384567299084+0.19759414972873335j),
  (0.22489384567299084-0.19759414972873335j),
  (11.158137723693127+0j)],
 [(0.006585957582150984-0.25738754788234897j),

In [80]:
backlist

[[1, 1, 1],
 [(-0.7448460967491979+0.8928146383229557j),
  (-0.7448460967491979-0.8928146383229557j),
  (0.7396921934983948+0j)],
 [(-0.2423222705612347-1.3300189969508007j),
  (-0.2423222705612347+1.3300189969508007j),
  (0.5471445411224667+0j)],
 [(1.3679532271082282+0.7743105881323611j),
  (1.3679532271082282-0.7743105881323611j),
  (0.40471854578355004+0j)],
 [(-1.710230449440062+0.644586446461388j),
  (-1.710230449440062-0.644586446461388j),
  (0.2993671488801146+0j)],
 [(0.6983622597417533-2.0070364788299355j),
  (0.6983622597417533+2.0070364788299355j),
  (0.2214395430164925+0j)],
 [(1.271739144661933+2.118441335639467j),
  (1.271739144661933-2.118441335639467j),
  (0.16379710130115147+0j)],
 [(-2.8386253728719546-0.44248543556072567j),
  (-2.8386253728719546+0.44248543556072567j),
  (0.1211594371501275+0j)],
 [(2.5093965032302368-2.204782736069264j),
  (2.5093965032302368+2.204782736069264j),
  (0.08962068982860871+0j)],
 [(0.09934811045724867+3.882649746581602j),
  (0.09934811

In [81]:
croots

array([-0.55095684-0.66040802j, -0.55095684+0.66040802j,
        1.35191369+0.j        ])

In [82]:
def vcoeff(croots):
    v=[]
    for a in croots:
        prod = 1
        for b in croots:
            if a!=b:
                prod *=b/a-1
        v += [1/prod]
    return v
    

In [83]:
vcoeff(croots)

[(0.27475402550206823-0.04260321557869386j),
 (0.27475402550206823+0.04260321557869386j),
 (0.4504919489958634+0j)]

In [84]:
I

[1,
 0.25,
 0.8125,
 1.390625,
 1.20703125,
 2.1572265625,
 2.835205078125,
 3.53375244140625,
 5.1670684814453125,
 6.777286529541016,
 9.103375434875488,
 12.525877237319946,
 16.73628741502762,
 22.681855216622353,
 30.74855660274625,
 41.434817978180945,
 56.101977163227275,
 75.85016437718878,
 102.4738419448986,
 138.6080609323435,
 187.3575610689486,
 253.26927791139337,
 342.4435512119033,
 462.92040730546944,
 625.8320431466882,
 846.0918674776774,
 1143.8174065349049,
 1546.3552953886724,
 2090.5437462260243,
 2826.2198146329156,
 3820.8180587164193,
 5165.413121879816,
 6983.186639140184,
 9440.674559911327,
 12762.971741212785,
 17254.435494376878,
 23326.512239415133,
 31535.426421849224,
 42633.17627940053,
 57636.37612565218,
 77919.40266281267,
 105340.30903934284,
 142411.0053825974,
 192527.38578796916,
 260280.4095232832,
 351876.64710439503,
 475706.85470653034,
 643114.608528212,
 869435.4402663457,
 1175401.671169276]

In [89]:
P = np.matrix(forwardlist)*np.matrix(vcoeff(croots)).T # prediction list

B = np.matrix(backlist)*np.matrix(vcoeff(croots)).T # prediction list # retro list

In [86]:
P[40]

matrix([[77919.40266281+0.j]])

In [87]:
I[40]

77919.40266281267

In [88]:
P

matrix([[1.00000000e+00+0.j],
        [2.50000000e-01+0.j],
        [8.12500000e-01+0.j],
        [1.39062500e+00+0.j],
        [1.20703125e+00+0.j],
        [2.15722656e+00+0.j],
        [2.83520508e+00+0.j],
        [3.53375244e+00+0.j],
        [5.16706848e+00+0.j],
        [6.77728653e+00+0.j],
        [9.10337543e+00+0.j],
        [1.25258772e+01+0.j],
        [1.67362874e+01+0.j],
        [2.26818552e+01+0.j],
        [3.07485566e+01+0.j],
        [4.14348180e+01+0.j],
        [5.61019772e+01+0.j],
        [7.58501644e+01+0.j],
        [1.02473842e+02+0.j],
        [1.38608061e+02+0.j],
        [1.87357561e+02+0.j],
        [2.53269278e+02+0.j],
        [3.42443551e+02+0.j],
        [4.62920407e+02+0.j],
        [6.25832043e+02+0.j],
        [8.46091867e+02+0.j],
        [1.14381741e+03+0.j],
        [1.54635530e+03+0.j],
        [2.09054375e+03+0.j],
        [2.82621981e+03+0.j],
        [3.82081806e+03+0.j],
        [5.16541312e+03+0.j],
        [6.98318664e+03+0.j],
        [9

In [90]:
B

matrix([[ 1.00000000e+00+0.j],
        [-9.71445147e-17+0.j],
        [-2.77555756e-17+0.j],
        [ 1.00000000e+00+0.j],
        [-7.50000000e-01+0.j],
        [ 3.12500000e-01+0.j],
        [ 9.53125000e-01+0.j],
        [-1.54296875e+00+0.j],
        [ 1.23144531e+00+0.j],
        [ 4.15283203e-01+0.j],
        [-2.16229248e+00+0.j],
        [ 2.74934387e+00+0.j],
        [-1.10615158e+00+0.j],
        [-2.02001476e+00+0.j],
        [ 4.54089284e+00+0.j],
        [-4.00681752e+00+0.j],
        [-1.50124833e-01+0.j],
        [ 5.65519084e+00+0.j],
        [-8.21067944e+00+0.j],
        [ 4.59408704e+00+0.j],
        [ 4.26229543e+00+0.j],
        [-1.25559228e+01+0.j],
        [ 1.29454553e+01+0.j],
        [-2.30781533e+00+0.j],
        [-1.40614251e+01+0.j],
        [ 2.40684779e+01+0.j],
        [-1.68438175e+01+0.j],
        [-7.44568145e+00+0.j],
        [ 3.38636934e+01+0.j],
        [-4.03801672e+01+0.j],
        [ 1.43735206e+01+0.j],
        [ 3.31785947e+01+0.j],
        